### ISSUE TITLE
Separate auth entirely from Laravel's Auth scaffolding

### ISSUE THREAD

**Issue by Ghitu** [Laravel-Backpack/base#10]
Make auth process separate from Laravel's Auth

- do not change the default views and controllers, just extend them

**Comment by tabacitu** [comment]
Rephrased: we should let the programmer make:auth and have a different auth entirely, that he can use for the front-end, if need be. This is not possible right now, because we overwrite the default Laravel auth views.

Changes that need to happen:
- views: instead of overwriting the Laravel views, we should publish them in views/vendor/backpack/base;
- controllers: instead of using the default laravel views, we should use the views above;
- controllers: instead of overwriting the AuthController and PasswordController functions just for changing the views, we should use Laravel's $loginView variables (and others like it);

That way, they will be completely separate.

**Comment by tabacitu** [comment]
Fixed in ed080e0151555eecadc40efbaf439ebdead70d1b (v0.6.0).
