### ISSUE TITLE
[Feature] Pre-published Extended PHP Classes

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#101]
When someone installs Backpack, he could also publishe all Backpack controllers, middleware and requests:
![Screen Shot 2017-02-05 at 16.10.09.png](https://shipusercontent.com/63a77ff6906f63314fa68056711640c0/Screen%20Shot%202017-02-05%20at%2016.10.09.png)

This would create blank classes inside your app folder. They would extend the ones in ```vendor/backpack/base/src``` but will have no methods. Because everybody is familiar with OOP and inheritance, they will instinctively know that in order to overwrite some Backpack functionality, you only need to define a certain method in that blank controller.

PROs:
- easier to customize PHP classes;
- easier to implement Backpack features that are only useful for that project;
- easier to understand how Backpack works (if it's in vendor, for a lot of people it's a "black box");

CONs:
- empty classes in your app folder;
- this ease of customization could determine some people to over-customize, making their apps very difficult to upgrade;

@OwenMelbz , what do you think? If we adopt this solution, we should do it for all Backpack packages, so there's a consistent way to interact with Backpack PHP classes.

**Comment by OwenMelbz** [comment]
You mean having something like 

<img width="684" alt="admincrudcontroller_php_ ___bravo_and__feature__pre-published_extended_php_classes_ _issue__101_ _laravel-backpack_base_and_gmail_-_owenmelbz" src="https://cloud.githubusercontent.com/assets/1094740/22627163/5f2fe156-ebb5-11e6-92cc-f928b6a7106e.png">

:D

I've been using a technique like this for a while now to allow an extra layer of control.

HOWEVER.

I'd like to think I know what I'm doing most of the time - but the issue I have with this is:

If people overwrite an existing method, it will make upgrading to later versions harder and debugging harder and offering support harder, because an unknown layer has been introduced - if we have to release a change in one of the methods, and people have over written it, then they wont get the changes.

That is my concern! however having something like `ApplicationCrudController` which is specific to that app thats published is a nice idea which I do like.

**Comment by tabacitu** [comment]
@OwenMelbz - that's my big fear too. Us publishing fixes and users not getting them because the methods are overwritten... Still undecided on this one. More feedback & opinions would be great.

Sorry, what do you mean by ```ApplicationCrudController```? An extension of ```vendor/backpack/base/src/app/Http/AdminController``` (which should probably be renamed to ```AdminPanelController```?

**Comment by tabacitu** [comment]
@OwenMelbz thanks for the great feedback, as always. I've given this a lot of thought and it looks like doing things like in this proposal would just cause more pain for us to maintain the packages.

So let's drop this and keep the classes inside the package. They can be easily overwritten/extended now thanks to the custom ```base.php``` routes file, but since this isn't _that_ easy to do, it will prevent people who don't know what they're doing to do it. I say that's a good compromise.

So...
![giphy](https://user-images.githubusercontent.com/1032474/30267004-ca9b1322-96e9-11e7-966f-c286dd43c67c.gif)
