### ISSUE TITLE
Request: make AdminLTE optional

### ISSUE THREAD

**Issue by juanem1** [Laravel-Backpack/Base#111]
Hi, AdminLTE is a great theme but for projects with GUI already designed is really complicated to integrate.
I think there is no need to force the users to use this theme, it would be great if the theme is optional and each user can decide if he want to download it or not.

Thanks.

**Comment by tabacitu** [comment]
Hi @juanem1 ,

That's planned, but it's considered a non-urgent issue. Since Backpack is open-source, we can't include paid themes. And for now, AdminLTE is by far the best-looking free theme I found, so we'll keep using it as default.

Using another HTML theme (or doing a custom design) should be pretty easy. It's just a matter of modifying layout.blade.php and maybe doing some changes in the general CRUD blade files. I've already done this twice, and it took me under 6 hours.

Pro tip: it's easier to create the CSS classes that AdminLTE uses for panels & blocks than going through all the files and modifying the HTML.

Cheers!
