### ISSUE TITLE
Create a form without a model

### ISSUE THREAD

**Issue by chancezeus** [Laravel-Backpack/Base#114]
For a project I'm working on I need to create a form without a model (it will be used for sending notifications). I know I can create a "dashboard" (#32) like solution, but would like to know how I can still access/use the crud field functionality...

**Comment by tabacitu** [comment]
Hi @chancezeus ,

Unfortunately, there's no easy way to use Backpack\CRUD without a model. But you can create a Notification model and use that, even if it stores nothing in the database. You'd just need to overwrite the ```store()``` and ```update()``` methods in your NotificationCrudController, to send notifications instead of storing them in the database.

Hope it helps.

Cheers!
