### ISSUE TITLE
Proposal: account preferences page

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/Base#116]
This should go hand-in-hand with @OwenMelbz 's "edit profile" section - https://github.com/Laravel-Backpack/Base/pull/88, which is in Top 2 important Base features I haven't merged yet. This feature, however, is a "nice-to-have".

**Premise:** there are certain settings we store in the session for users; not about how the admin panel works for everyone, but how it works _for them_;

**Problem:** (small one, i'll give you that) session storage isn't persistent across devices; and even goes away when deleting cache, using another browser, etc; it does not provide a consistent experience for the admin;

**Solution:** In "My account", we can create a "Preferences" page, where the admin can toggle/choose how the admin panel can better fits his needs; the settings would be stored in the db (or in the session, that is then stored in the db and replentished if missing); the user would then have a single place to toggle preferences _for his account_, from different backpack packages (or new preferences inserted by the developer); examples:
- when first collapsing the sidebar menu, we ask the admin "would you like to always keep the sidebar collapsed? [Only today][Yes][No]"; we store his preference;
- when first using a different CRUD save_action than the default, we ask the admin "would you like to always use **Save and add another item** as your default? [Only today][Yes][No]"

What do you think? Useful or overkill?

**Comment by OwenMelbz** [comment]
Overall sounds useful :)

My suggestions would be to carefully name this system to make sure it doesn't pollute the application namespace, so something like BackpackPreference::class to keep it obvious

I think asking the user when they first do something is overkill, if the user changes something let it just stay there, they changed the setting by collapsing the menu so that should be enough. (Also easier logic and less overhead)

However sure we can deffo allow them to edit these in their account area :)

If I were to do it that is how I'd go about it!

**Comment by lloy0076** [comment]
@

**Comment by lloy0076** [comment]
@ow

**Comment by lloy0076** [comment]
@tacabitu @owenmelbz what do we do with https://github.com/Laravel-Backpack/permissionManager and its user manager?

Does this belong in that rather than base?

**Comment by tabacitu** [comment]
On second though, this might be overkill. Too few projects actually need this and it's easy to hardcode, so it doesn't make sense to have it in the core. Closing, let me know if you disagree.
