### ISSUE TITLE
Auth route names

### ISSUE THREAD

**Issue by gboor** [Laravel-Backpack/Base#117]
I am using Laravel's default auth for user auth on the website and Backpack auth for admins specifically. I set up the separate guards and all that - not an issue.

The problem is that Backpack uses Route::auth() to generate its auth routes. Even with the admin (or custom) prefix set, the routes will still get the default route NAME passed as ->name('login') (or similar) - this breaks Laravel's auth; once the Backpack routes override the regular Auth routes, a post to route('login') will result in POST-ing to /admin/login instead of /login, etc.

Not a major issue, since I can change all the front-end forms involved, but it might be nice to have a setting for route name prefix as well, so these routes are generated as admin.login (or similar).

**Comment by TesseractG** [comment]
Addendum; for some weird reason, even if I use url('/login') in the front-end, it STILL redirects to /admin upon login, instead of the redirectTo set in LoginController...

**Comment by MarcosBL** [comment]
Is this of any help? https://laravel-backpack.readme.io/docs/frequently-asked-questions#section-customizing-the-routes

**Comment by TesseractG** [comment]
Sadly, it does not... I am aware of that FAQ. Of course I can set up all the routes manually, but that is a workaround, not a fix (I have done so currently).

The issue is that I want to use BOTH admin auth AND website auth for 2 different groups of users. I managed to set up 2 guards and all that works fine.

Using the standard config of Backpack, it issues a Route::auth() somewhere in the backpack setup, which sets up the /admin/login and /admin/logout and what not - all fine.

However, Route::auth() *also* sets these routes up with *names*, like so;

$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');

Since Backpack registers its routes first, all subsequent calls in the application to route('login') will generate a URL that points to the *admin* login. Since I use the default Laravel auth scaffolding, this is a bit problematic, since the scaffolding and email templates, etc. are full of route('login'), route('password.reset'), and so on and so forth - all of which by default now point to these procedures on the admin panel.

The only way I was able to fix this is by indeed disabling the admin panel auth routing and adding all routes manually with the admin. prefix in the name. I just feel that the route *names* should also be prefixable from config and perhaps Backpack should not internally use Route::auth() to set up its own scaffolding.

**Comment by mashhoodrehman** [comment]
@gboor bro did u resolved the issue add admin before login

**Comment by gboor** [comment]
I resolved it by manually adding all the routes I need for backpack and not calling the backpack route setup. Note that this was before the latest release, so this might be fixed now. I still need to check.

**Comment by pjhartin** [comment]
@gboor I can confirm I am in the same situation and will probably have to do the same as you have described. Thanks for letting us know it works for you.

**Comment by lloy0076** [comment]
I think this issue is resolved; please re-open if it isn't.
