### ISSUE TITLE
How to set custom favicon to backpack admin panel?

### ISSUE THREAD

**Issue by Simpson1993** [Laravel-Backpack/Base#138]
Does Backpack have some stuff for easy set custom favicon?

**Comment by tabacitu** [comment]
Hi @Simpson1993 .

This doesn't seem Backpack-specific so I'll close the issue. 

But I strongly recommend [realfavicongenerator.net](https://realfavicongenerator.net/) - I'm very happy with it. It will help you generate all the files you need, and the HTML to go along with it. You'll then be able to use the favicons by placing them in your ```/public/``` folder and using that HTML in you blade template. Place it in ```resources/views/backpack/base/layout.blade.php``` too, if you want the same favicon on the backend.

Hope it helps.
Cheers!

**Comment by cweiske** [comment]
I think this is backpack-specific, because if you use `backpack-crud`, which uses the layout from `backpack-base`, there is no way to add a custom admin favicon because there is no way to change the layout requested by the `backpack-crud` views AFAIK.

The question is how to set the favicon for the whole admin area to a different image than the main web application.

**Comment by ariaenggar** [comment]
So if I just want to add one line favicon in <head></head> then I must override the inc/head.blade.php?
