### ISSUE TITLE
Where to do additional of parameter during login?

### ISSUE THREAD

**Issue by milanchheda** [Laravel-Backpack/Base#163]
Hi there,

I have added a column in users schema namely 'verified'. I want to check this column whenever user tries to login. 

How and where should I write this piece of code?

**Comment by lloy0076** [comment]
This, really, is an upstream question.

You probably want to checkout the `authorized` public function in `app/Http/Controllers/Auth/LoginController` though.

Something like:

```
 93     /**
 94      * The user has been authenticated.
 95      *
 96      * @param  \Illuminate\Http\Request  $request
 97      * @param  mixed  $user
 98      * @return mixed
 99      */
100     protected function authenticated(Request $request, $user)
101     {
102         if (! $user->verified) { die('oh no you do not'); }
103
104         return redirect()->route('dashboard');
105     }
```

**Comment by milanchheda** [comment]
@lloy0076 - Well, I did tried that and it was the obvious solution, but somehow it never goes into this function. So I thought, may be, backpack has some setting or some other way to do this.

**Comment by tabacitu** [comment]
Hi @milanchheda ,

Backpack uses its own LoginController. That's where you'll need to modify the method. In order to easily replace the LoginController with your own, you can use this feature we just pushed, where you can [easily customize the routes](https://github.com/Laravel-Backpack/Base#overwriting-functionality).

Hope it helps.

Cheers!

**Comment by milanchheda** [comment]
Cool. Will update the package and try it out. Thanks @tabacitu.
