### ISSUE TITLE
login in the auth scaffolding redirect me to admin dashboard.

### ISSUE THREAD

**Issue by HassanOumar** [Laravel-Backpack/Base#171]
Hi everyone i hope you all having a wonderful day.

I have little problem with login functionality,
i run php artisan make:auth, when i login to my website it's redirect me to admin dashboard, even thought i have not changed any thing, just run the basics command,

in my login controller the redirect variable is to "home", so why it's redirecting me else where.

**Comment by lloy0076** [comment]
This might best be asked at https://stackoverflow.com/questions/tagged/backpack-for-laravel.

That said:

1. What version of Laravel are you using (with the recent L5.5 release this may help to know and some people are using L5.3 still);
2. Did you follow the steps in the documentation?

I think I actually do know what's happened to you, though, because it's just happened to me.

If you setup a default L5.5 installation and follow the instructions, doing what you did, then you'll end up with two sets of Auth routes, neither of which do exactly the same thing but they'll both call the login route `login` (and register route `register`) - and you'll get confused.

My advice:

1. In `routes/web.php` remove any reference to `Auth::routes()`;
2. Choose whether to have backpack setup the routes in `config/backpack/base.php` (you probably should leave this at `true` for the moment);
3. See if things work.

**Comment by tabacitu** [comment]
I'm pretty sure this is the same issue as this one - https://github.com/Laravel-Backpack/Base/issues/117 . So let's talk there.

Cheers!
