### ISSUE TITLE
Laravel 5.5 support?

### ISSUE THREAD

**Issue by rickmills** [Laravel-Backpack/Base#172]
The inevitable question - will Backpack be updated for 5.5 any time soon?

**Comment by OwenMelbz** [comment]
When you say "updated" is there anything you've found not to be working? As far as I'm aware theres no breaking changes in 5.5 yet except for a potential php 7.1 requirement bump.

We're using something like `"laravel/laravel: "dev-master as 5.4"` in our composer.json theres no initial errors we're getting.

As this isn't actually a bug I will close this ticket to keep the area tidish however I'm sure @tabacitu will see it regardless :)

**Comment by tabacitu** [comment]
YES :-) [that was a big yes. kind of defeats the purpose if I have to explain it though :D]

We actually have a history of synchronising our breaking changes with Laravel's, so that it's easier to upgrade existing projects - you can upgrade both in one go. That being said, as Owen mentioned, Backpack is already working in 5.5, so we're ready. But this does bring the opportunity to push some breaking changes so can't wait for it to be released so we can push some awesome new features ourselves :D

**Comment by kocoten1992** [comment]
I didn't know I could do that  ```"laravel/laravel: "dev-master as 5.4"``` :scream:

**Comment by rickmills** [comment]
Awesome thanks guys :)
