### ISSUE TITLE
Add support to Laravel 5.5

### ISSUE THREAD

**Issue by strikermdd** [Laravel-Backpack/Base#176]
Please, add support to Laravel 5.5 and AutoPackage Discovery function!

Thanks for this great package.

**Comment by lloy0076** [comment]
As far as I can tell, most if not all of the current packages (base is just that - the base) work with Laravel 5.5; some of the packages already have PRs or branches with auto-package discovery.

Thanks for the thanks -  at the moment base doesn't have an issue re: L5.5 compatibility that I can see, so I'll keep this one open unless @tabacitu thinks there is an overarching issue to handle it.

**Comment by mpixelz** [comment]
L5.5 is out 😄 
looking forward to backpack updates too 😄

**Comment by tabacitu** [comment]
Thanks for the update, @mpixelz . I've just pushed the compatibility fix, Backpack now officially supports Laravel 5.5 :-)

It will take a little more time to merge and push all the new features into CRUD 3.3, though. I expect we'll have the new CRUD release by Friday. But until then, this latest fix (Base 0.7.24) makes it so that Backpack is installable on shiny new Laravel 5.5 projects, with no new Backpack features. 

I think the big upgrade will come as Backpack\Base 0.8.0 and Backpack\CRUD 3.3 and will _only_ support Laravel 5.5.

@strikermdd yup, package autodiscovery is what I'm working on right now. Finally getting to strip down the installation by a few steps, whoop-whoop!

**Comment by mpixelz** [comment]
looking forward for the major release of backpack as well. so we have all the breaking changes and the update at the same time 😄 
thanks @tabacitu :)

**Comment by mpixelz** [comment]
the installation instructions for 5.5 are still using dev branch.. just pointing if you've forgotten about them :)
@tabacitu

**Comment by tabacitu** [comment]
Hi @mpixelz ,

Thanks for the heads-up. Do you mean these?
```
composer require backpack/generators --dev
composer require laracasts/generators:dev-master --dev
```
If so, that's ok, it's so that they're installed on ```require-dev``` by composer.

Cheers!

**Comment by bocha95** [comment]
@tabacitu I've everything installed.

**But when I try to:**

php artisan make:migration:schema create_stores_table --schema="name:string:unique" --model=0

**I get:**

  [ReflectionException]
  Method Laracasts\Generators\Commands\MigrationMakeCommand::handle() does no
  t exist
