### ISSUE TITLE
Integrating ArcaneDev-LogViewer in Laravel-Backpack

### ISSUE THREAD

**Issue by eduardoarandah** [Laravel-Backpack/Base#179]
I modified ArcaneDev-LogViewer views to work with backpack admin layout

Might be of your interest

https://github.com/eduardoarandah/Laravel-Backpack-ArcaneDev-LogViewer

![xx](https://user-images.githubusercontent.com/4065733/29938257-cd848f5e-8e4d-11e7-89e1-604e352f158f.png)

**Comment by lloy0076** [comment]
@tabacitu - what's the process for listing packages that may not necessarily be part of the **core** of Backpack but are of interest to the project?

@eduardoarandah - thanks for the work and it looks good - I won't close this yet but I sense we're slowly trying to wrestle the issues into "issue" 😃

**Comment by eduardoarandah** [comment]
Maybe a section "Examples and contributions" in https://laravel-backpack.readme.io/docs ?

Some features are very common and might be of interest for new backpack users to copy-paste them

Like this

![asdf](https://user-images.githubusercontent.com/4065733/30060822-908f7b84-920a-11e7-9c31-980e9b2aa794.png)

**Comment by tabacitu** [comment]
This. Is. AWESOME! I've been unhappy with LogManager for a long long time, and ArcaneDev does an excellent job, I agree. Let me test it out and see how we can encourage more people to use it.

**Comment by tabacitu** [comment]
@eduardoarandah , I do agree with using ArcaneDev-LogViewer instead of the simple stuff LogManager does, but I think a better approach would be to provide full-service, rather than a quick fix.

**What do you think of making it a composer package?** Then it would truly be an alternative to LogManager, if the installation process is similar, and it's pretty much plug-and-play. I would definitely recommend people to install your package instead of LogManager, since it has a lot more features. It would show up on the website alongside LogManager and other packages and in the upcoming Backpack package marketplace.

What do you think? Are you willing to do that? Do you need help getting started? I know this [great article on creating Laravel packages](https://medium.com/@tabacitu/creating-laravel-5-packages-for-dummies-ec6a4ded2e93) from this brilliant guy. His way of thinking is so similar to mine...

That being said, I'll close this issue so it doesn't show up as open, but let's keep talking about this. I'll also raise a few issues I've found [here](https://github.com/eduardoarandah/Laravel-Backpack-ArcaneDev-LogViewer/issues).

Cheers!

**Comment by eduardoarandah** [comment]
Yes! Great idea 

Thanks for the article, I've never made a package, definitely will do it.
