### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by chimmel** [Laravel-Backpack/Base#218]
# Bug report
Times out

### What I did:
Tried `composer require backpack/base` which said `The process "composer require backpack/generators --dev" exceeded the timeout of 60 seconds.`
Separately installed generators, supposedly loaded base successfully adding it manually and updating, now can't get past `php artisan backpack:base:install`:

```
### Backpack\Base installation started. Please wait...
### Running: composer require backpack/generators --dev

  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "composer require backpack/generators --dev" exceeded the timeout o
  f 60 seconds.
```

### What I expected to happen:

Success

### What happened:

Issues

### Backpack, Laravel, PHP, DB version:

Laravel 5.5, backpack/base 0.8.2, PHP 7

**Comment by lloy0076** [comment]
This can be worked around by doing `composer require backpack/generators --dev` manually and then rerunning install.

**Comment by lloy0076** [comment]
Closing in favour of #217.

**Comment by chimmel** [comment]
Except I tried that...

**Comment by lloy0076** [comment]
@chimmel --

* What OS?
* PHP version?

If you do a `composer rqeuire backpack/generators --dev -vvv` do you see any apparent errors (does that work _at all_?).

**Comment by tabacitu** [comment]
I have no idea what the issue was... It looks like the official composer repository skipped a beat for this package. It's happened to me for other packages before, but it has been fixed in a matter of hours. This time it sounds like it took a little longer...

I've just tested it, on a fresh install, and it works fine now. Since there's nothing we can do about this (or nothing that I know of) I'm going to close the issue. But please reply here if anybody has this problem again in the future... We'll see what we can do...
