### ISSUE TITLE
No styles and scripts are loaded after installation

### ISSUE THREAD

**Issue by NaveNO** [Laravel-Backpack/Base#224]
# Bug report

### What happened: **after entering /dashboard I saw page with no styles and scripts. Screenshots: 
![image](https://user-images.githubusercontent.com/13716167/33528002-3ab1b5c2-d86b-11e7-8549-817af76a22a3.png) 
![image](https://user-images.githubusercontent.com/13716167/33528013-755b7208-d86b-11e7-8390-9be5a64e7423.png)

**

**Comment by tabacitu** [comment]
Hi @NaveNO ,

Thanks for the comprehensive bug report. Just tested it and it didn't happen to me on a fresh install. So it should be isolated on your machine. But it's very odd. I see the css/js assets have been copies successfully, the installation process went well.

My first thought - **maybe it's because you're serving it over HTTPS?** Chrome sometimes refuses assets that are served over _unsigned_ HTTPS. What if you change your environment to use HTTP instead? Would that fix it?

Cheers!

**Comment by MDEvo** [comment]
On vendor/backpack/base/src/app/Console/Commands/Install.php

Change to this (swap the single and double quotation ):

`$this->executeProcess('php artisan vendor:publish --provider="Backpack\Base\BaseServiceProvider"', 'publishing configs, langs, views and AdminLTE files');
        $this->executeProcess('php artisan vendor:publish --provider="Prologue\Alerts\AlertsServiceProvider"', 'publishing config for notifications - prologue/alerts');`

**Comment by tabacitu** [comment]
Oh, ok, thank you @MDEvo . The latest Base version now has this change https://github.com/Laravel-Backpack/Base/pull/220/files , thank you!
