### ISSUE TITLE
change admin LTE to Coreui bootstrap 4

### ISSUE THREAD

**Issue by vahidalvandi** [Laravel-Backpack/Base#234]
i use 
http://coreui.io/demo/Ajax_Demo/#main.html
i my project it very light weight and update but admin lte is slow.

if i upgrade laravel-backpack you can merge pull request ??

**Comment by lloy0076** [comment]
I'm not sure whether you're saying:

1. AdminLTE is too slow;
2. Backpack is too slow;
3. You've already written a bunch of code to replace the Backpack views to use CoreUI and want to make a merge request;
4. Something else.

AdminLTE isn't - in and of itself - slow.

What is the problem you're trying to address?

**Comment by vahidalvandi** [comment]
Core ui have better UI and total size in 50% increased and use bootstrap 4

**Comment by lloy0076** [comment]
I'm sure you'd be welcome to rewrite the underlying admin structure and views to use CoreUI but I very much doubt that @tabacitu (or the rest of the team) would contemplate replacing AdminLTE in a near future version, especially since "a better UI" is somewhat subjective.

**Comment by tabacitu** [comment]
Woow... I'm impressed. CoreUI does seem blazing fast, I agree with that one :-) And it looks so much like AdminLTE, it's silly. But @vahidalvandi I don't think this is the right time to switch from AdminLTE to CoreUI, since this would be a major breaking change. I think it's something for Backpack v4.

I expect we'll be able to **_start_** work on Backpack v4 in Q3-Q4 this year. If AdminLTE doesn't move to Bootstrap 4, I agree, we should could switch to CoreUI. But we need to check the CoreUI license and coding style too - personally I've chose AdminLTE because I think their code is clean and clear. Sure, it uses too many divs and comments, but that was a compromise worth making imho. If CoreUI's code style is reasonable too, I see no reason not to switch, if AdminLTE does not move to Boostrap 4. Even if it does, I think it's a good milestone, where we can take a breath and count our options. The license is also very important, I see CoreUI has a duallicense just like Backpack so I think we could make it work...

Until Q3-A4 though, @vahidalvandi , if you want to use CoreUI with Backpack 3, I'm afraid your only option is to use custom ```blade``` files. As you might know, anything you put in ```resources/views/vendor/backpack/base``` (or crud, or any other backpack package) will overwrite that file from the package. If you do that for one of your projects, a PR would be so SO helpful if we do decide to make the switch, so it's greatly appreciated.

Thanks, cheers!

**Comment by tabacitu** [comment]
I've [open a disussion with the collaborators](https://github.com/orgs/Laravel-Backpack/teams/community-members/discussions/11), so let's close this issue for now.

**Comment by bloggervista** [comment]
Core UI with Vue or react version would be perfect

**Comment by Omegatcu** [comment]
@vahidalvandi If you are interested I would help with this and we could make a package out of it to support the theme. Then people can decide to pull our package in and replace the AdminLTE views for Crud and co. Ping me if you are interested.

@tabacitu I think with the overrides you did a pretty good job, this helps a lot to make a new theme work. I admit that AdminLTE has the clean code but so have a lot of other Templates and AdminLTE is just "outdated" in a way. You also see it almost everywhere which can be quite annoying.

I like the way Backpack is handling stuff a lot more, especially for CRUDs but if you look at craftable for instance, damn have they a nice UI.

**Comment by iMokhles** [comment]
CoreUI is looks good but let's see what v3 of AdminLTE will bring to us as it's already WIP :)
https://github.com/almasaeed2010/AdminLTE/tree/v3-dev

**Comment by tabacitu** [comment]
@iMokhles totally agree.

**Comment by tabacitu** [comment]
@Gog0 - omg tabler is so beautiful and simple. I saw it when it launched. Love it :-) Really makes me want to prioritize this themes feature in Backpack, but it's a big one.

**Comment by iMokhles** [comment]
@tabacitu I can try to integrate it with the demo repo to see what it looks like with Backpack for Laravel :wink:

**Comment by tabacitu** [comment]
Thank you @iMokhles . I can already see it - it'll look beautiful :-) Let's postpone this until we support themes, which should be soon. Let's not code something twice. You can then create the "tabler" theme, if you want, I myself will definitely use it for most projects :D There are some problems with tabler though, mainly the fact that it doesn't have a sidebar menu... but I'm sure we'll figure something out.

**Comment by danielbidala** [comment]
Any news with a BS4 template)? Core UI is very promising... AdminLTE 3 is still in alpha. It seems BS5 will be out there when Admin LTE 3 goes stable... :)

**Comment by shirshak55** [comment]
For me adminator is the best ui I have ever seen

https://github.com/puikinsh/Adminator-admin-dashboard

After that tabler is one

But I still recommend Adminator Theme

And yes admin lte will be ready when bootstrap 5 will release :D

**Comment by AbbyJanke** [comment]
Themes is something that is being planned for Backpack 4 however there is no ETA for it at the moment.
