### ISSUE TITLE
Redirect Path on click of logout and password reset.

### ISSUE THREAD

**Issue by DrudgeRajen** [Laravel-Backpack/Base#24]
This package is awesome . :+1:  I am playing with it from last few hours. Also, i cloned the demo project and i am going through it . I don't know if it is bug or i am mistaken but there is issue. 

1. When clicking on logout button, it redirect me to the base url (i.e. localhost/project/public). And i think it should redirect the user to the login page. 
2. And when user reset the password by clicking in the link that is being send in email, it redirect to /home i think which is default Auth redirection. 

So, when i keep the redirect path in AuthController and PasswordController it is working. 

In Password Controller i just kept 

```
/**
     * Where to redirect users after password reset.
     *
     * @var string
     */
    protected $redirectTo = 'admin';

```

And in AuthController 

```
/**
     * Where to redirect users after login / registration / logout.
     *
     * @var string
     */
    protected $redirectTo = 'admin';
    protected $redirectAfterLogout = 'admin/login';

```

If this is bug/issue then i will glad to send the pull request .

**Comment by DrudgeRajen** [comment]
Hello,
Yes you are right , developer may wants to redirect to different path . Instead of using hardcode redirect path, path in the base config will be best option. I will keep the option in the config and will send pull request ASAP.

**Comment by DrudgeRajen** [comment]
Hello @tabacitu ,

I forked the package in  my package directory but i the package is not loading in the app . i.e. Service provider is not loading its config . What may be the reason ? Can you help me with this ?

Thank you

**Comment by tabacitu** [comment]
I think you should autoload the package in your composer.json, in your psr-4:
```
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "Backpack\\Base\\": "packages/backpack/Base/src",
            [...]
        }
```
(careful - it's case sensitive)

**Comment by DrudgeRajen** [comment]
Yeah i have done that all . But it's not loading . I know laravel is not loading the package after doing all those things ,because i when i use the base route i.e. localurl/admin/login. I am getting 

> NotFoundHttpException in RouteCollection.php line 161:

So, can you show me the way how to debug it . I also echoed some text `echo ('test');` in the boot function of BaseServiceProvider but i am getting the same thing again and again . What might me the issue ? Any guesses ?

**Comment by tabacitu** [comment]
Hmm.. So:
1) when you echo the text, does it echo it? these things are massive time-wasters, because in my experience it's usually a typo.
2) did you do a ```composer dump-autoload```?
3) if you can't make it work this way, you could [install the package from your own repository using composer](http://lornajane.net/posts/2014/use-a-github-branch-as-a-composer-dependency)

**Comment by DrudgeRajen** [comment]
Nope it doesn't echo any thing. And yes i did composer dump-autoload  , but same result. :( 

Okay will try next method then . 
Thank you for your suggestion .

**Comment by DrudgeRajen** [comment]
Hello @tabacitu 
I am able to use the package . But now css and js not working  . Is there any thing i am missing ?

**Comment by tabacitu** [comment]
Did you [publish the assets](https://github.com/laravel-backpack/base#install)?

**Comment by DrudgeRajen** [comment]
While trying to publishing the assets i am getting 
`Can't locate path: </var/www/opensourceprojects/laravel-backpack/vendor/almasaeed2010/adminlte>`

**Comment by DrudgeRajen** [comment]
Hello @tabacitu ,
Sir, can you show me the way to fix this issue so that i can send pull request ??

**Comment by tabacitu** [comment]
Hi @DrudgeRajen ,

Unfortunately, I've discovered what we were planning is impossible that way. It should have been obvious, I don't know why I missed that. You can't use the ```config()``` helper to set a property on a class. This:
```php
protected $redirectTo = config('backpack.base.redirectTo');
```
won't work.

So the only option I see in order to achieve your goal is to overwrite the AuthController. I've made that easier to do in Backpack\Base v0.6.12. After a ```composer update``` you can [follow the steps here](https://github.com/Laravel-Backpack/Base/issues/25#issuecomment-238011374). Please let me know if this works for you or not.

Sorry you couldn't submit a pull request this time - I really like to merge pull requests, it makes me realize I'm not the only one pushing this project forward. Next time, I guess :-)

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.

**Comment by DrudgeRajen** [comment]
@tabacitu 
No worries :) . But the thing is i am not able to publish the assets of the package :( . Can you help me with that ?

**Comment by tabacitu** [comment]
I'm almost certain that that's because the package did not actually register. Try a ```dd('it got here');``` in your BaseServiceProvider's boot() method to check. If you can go to the homepage of the app without the text showing up, it means the package did not register and boot. For me, most of the times it's a typo in composer.json or forgot to do ```composer dump-autoload```.

**Comment by DrudgeRajen** [comment]
Nope the package had register there . I can get the  "it got here" in BaseServicePovider's boot() method but the problem the application is not loading css and js .

**Comment by tabacitu** [comment]
Did you publish the assets? Do you have everything you need in your ```public/vendor/admlte``` and ```public/vendor/backpack``` folders?
