### ISSUE TITLE
Default Admin Access?

### ISSUE THREAD

**Issue by InkedCurtis** [Laravel-Backpack/Base#261]
Currently I've got a project in which I need to have my own user panel (not backpack & managed within my app) but uses the `users` table, this being the case they're also granted access to login/access at **site.com/admin**?

How can I change this authentication so I can create a new column in my `users` called `admin` with a simple `ENUM('0','1')` which permits them access or not to the **/admin** paths

Or does this already kind of capability already exist within Backpack & I'm just overlooking it?

**Comment by InkedCurtis** [comment]
Or maybe somehow to do something like this & have a separate table for admins? #56

**Comment by tabacitu** [comment]
Hi @InkedCurtis ,

Starting with the next Backpack\Base 0.9.x (due this week), you'll be able to customize the "admin" middleware. So basically you'll be able to tell that middleware to check that the ```admin``` column in your db is 1. [Here's the PR for it](https://github.com/Laravel-Backpack/Base/pull/258).

Until then, you should be able to achieve the same thing by [overwriting the Base routes](https://github.com/laravel-backpack/base#overwriting-functionality), and instead of using the ```admin``` middleware, using your own middleware, that checks that ```admin == 1```. When the update rolls around, you'll be able to delete that ```base.php``` _routes file_ and point your ```base.php``` _config file_ to your custom middleware.

Hope it helps.
Cheers!

**Comment by tabacitu** [comment]
IMHO for simple use cases, an admin table is overkill. An ```is_admin``` (bool) column in the db should do just fine, **as long as it's not fillable in the model**.

**Comment by InkedCurtis** [comment]
@tabacitu I see it's been merged, how would I go about doing this? any documentation mate?
