### ISSUE TITLE
Full AdminLTE repository

### ISSUE THREAD

**Issue by nicolas-t** [Laravel-Backpack/Base#266]
# Bug report

### What I did:
I went to my public/vendor folder

### What I expected to happen:
See assets

### What happened:
I saw a whole repository of 300k+ lines

### What I've already tried to fix it:
deleting it

### Backpack, Laravel, PHP, DB version:
0.7.16

Hello,

Is it normal for the repository https://github.com/almasaeed2010/AdminLTE (1900 files) to be present in my `public/vendor` folder ? 
Can't it be installed with composer ? in the `vendor` folder ?

Thanks

**Comment by tabacitu** [comment]
Hi @nicolas-t ,

I agree it's somewhat annoying to have all AdminLTE files both in ```/public``` and in ```/vendor```, but this has been the best practice in Laravel packages so far - to publish the assets to the public folder. Since those files are CSS, JS and images, they need to be publicly available, with a simple URL. Hence, ```/public```. 

That being said - I do think we can do better. Upon Backpack\Base installation, we could:
- create a ```/public/vendor/adminlte``` symlink to the ```/vendor/almasaeed2010/AdminLTE``` folder; [just like Laravel itself suggests for ```storage/app/public```](https://laravel.com/docs/5.6/filesystem#configuration);
- add a public filesystem disk to that symlink (we could call it ```adminlte```);

The way I see it:

PROs:
- saves disk space (currently 49.7 MB);
- makes sure developers don't modify AdminLTE files (since they're in ```/vendor```);
- we get automatic updates for AdminLTE assets upon ```composer update```; 

CONs:
- [solvable] _as far as I know_, symlinks only work in Unix environments; what about Windows developers? there must be a solution for them too, we could do whatever ```php artisan storage:link``` does for Windows; 
- [solvable] it could be a breaking change; but I think if we keep the symlink in ```public/vendor/adminlte``` this could be included as a non-breaking change; 
- would this expose the ```/vendor/``` folder in any way? 'cause that would be _really_ bad;
- we get automatic updates for AdminLTE upon ```composer update```; this can be viewed both as a PRO and as a CON; if AdminLTE pushes a breaking change as a non-breaking change, there's no way for us to fix it, since we use their files directly; 

Will look at this again in a while, this needs to be carefully considered, since it would be an important change. Any feedback - anyone else?

Cheers!

**Comment by bluec** [comment]
Seems this is covered in more detail in an issue on the CRUD repository: https://github.com/Laravel-Backpack/CRUD/issues/1404

**Comment by Jamesking56** [comment]
I second this, an entire repo shouldn't need to be made public

**Comment by vesper8** [comment]
really hoping for a better solution in V4. The main problem is the bower_components folder.. that folder alone weighs over 40mb and has a ton of non-essential files in it. I'm sure if you stripped all the fodder and only kept the dist files and required files such as css and fonts you could reduce 40mb to 1 or 2mb

it would be lovely to consider using a Vue fork of AdminLTE as an alternative.. such as Copilot maybe or something else. What I love about vue projects is the dependencies are all compiled as part of the dist folder when you build so there's no reason to include the full dependency folders (as is currently the case with bower_components). Vue smartly only keeps what is needed and shaves off all the rest

**Comment by tabacitu** [comment]
Totally reasonable @bluec & @vesper8 - thank you for your take on this. I'll keep you guys updated when we decide for something in v4 - this decision is due soon. Thanks a lot for your input! In my opinion, the best solution so far would be to publish a minimum amount of files, and re-publish them on every Backpack upgrade, like @vesper8 suggested here - https://github.com/Laravel-Backpack/CRUD/issues/1404#issuecomment-450494462

I'll close this issue, as there's a more detailed talk there. Please join us.

Cheers!
