### ISSUE TITLE
backpack_avatar_url not working for custom method

### ISSUE THREAD

**Issue by bauersfeld** [Laravel-Backpack/Base#278]
# Bug report

### What I did:
In base.php config file, I set backpack.base.avatar_type = 'my_custom_url'

### What I expected to happen:
To call my custom method on the user model to return an avatar url

### What happened:
Helper function backpack_avatar_url complains because it doesn't have proper method syntax

### What I've already done to fix it:
       default:
                return $user->{config('backpack.base.avatar_type')}(); // <- added closed parens
                break;

**Comment by yaim** [comment]
That's right, variable functions need the parentheses.
Fixed in #281

**Comment by dividy** [comment]
Nice! 

That's exactly what i meant here : #275

**Comment by tabacitu** [comment]
Ouch. Now I understand what you were saying, @dividy - sorry for being so dumb. The description is deceiving - it was asking you to specify **a method**, but it was actually calling **an attribute**. 

Thanks a lot for the PR @yaim , I've just merged it and made both available, so that this change is backwards-compatible. If a method with that name exists on that model, it will load it. Otherwise it will fall back to the accessor, like it was before. This way, @dividy 's and others apps won't break because of this.

Thanks, cheers!
