### ISSUE TITLE
backpack:base:add-custom-route bad placement on routes custom.php

### ISSUE THREAD

**Issue by jorgepires** [Laravel-Backpack/Base#299]
Hi, I am trying Backpack for the first time, and while reading the official tutorial I followed the instructions to create the Tag example.

At certain point it states:
php artisan backpack:base:add-custom-route "CRUD::resource('tag', 'TagCrudController');"

While the line is added to the custom.php in routes, it seems to be added in the wrong position:

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
}); // this should be the absolute last line of this file
 CRUD::resource('tag', 'TagCrudController');

While, as pretty well commented on the file, that is not the last line, so I perfomed the fix below:

Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
     CRUD::resource('tag', 'TagCrudController');
}); // this should be the absolute last line of this file

Using Laravel 5.6 with PHP 7.1.1 and MariaDB 5.5

**Comment by tabacitu** [comment]
@jorgepires you're totally right - thank you for pointing this out. Just pushed an update that fixes this, and the route is placed correctly on all operating systems now. A ```composer update``` should fix it for you.

Cheers!

**Comment by rinodung** [comment]
Get this error line 55:
```
$file_lines[$end_line_number + 1] = $file_lines[$end_line_nu
mber];
```
![image](https://user-images.githubusercontent.com/7805715/44867080-1a959680-acb1-11e8-82b8-5f1691de19c3.png)

**Comment by Benjamest** [comment]
Same issue here @rinodung. Did you ever get this resolved?

**Comment by tabacitu** [comment]
@rinodung I'm afraid we can't use ```\n``` since not all systems use that. Some use ```\r\n```. But I _think_ replacing the explode with ```$file_lines = preg_split('/\r\n|\r|\n/', $old_file_content);``` would fix it for all systems...

I believe the problem here is that:
- this file is written on Unix, which uses ```\r\n```, that's the end line type encoded into the file;
- your Windows system uses ```\n```, so when splitting the file it does not split it correctly;

If so, that should fix it. I can confirm it still works on Unix systems, hopefully you can confirm it also works on Windows.

PR here: https://github.com/Laravel-Backpack/Base/pull/316
