### ISSUE TITLE
How to change backpack template without edit in the vendor folder?

### ISSUE THREAD

**Issue by iamtung** [Laravel-Backpack/Base#306]
Hi,
I was buy a admin dashboard template in themeforest and i want to change the default template of backpack. I just found some ways by edit the vendor folder. But i don't want use this way because i have a team, and in .gitignore, we added the vendor folder.
So is have any way to change the backpack template without edit in the vendor folder?
Thank you so much.

**Comment by iamtung** [comment]
Thank, i will find help in gitter.

**Comment by rudolphp** [comment]
https://github.com/Laravel-Backpack/CRUD/issues/903 - this post might help

**Comment by tabacitu** [comment]
@iamtung there are a few vendor folders in your project:
- ```/vendor``` - stores packages installed by composer; modifications here will get overwritten upon ```composer update```; should not overwrite;
- ```/public/vendor``` - stores js/css files that different packages use; you _can_ overwrite this, but at your own risk;
- ```/resources/views/vendor``` - stores blade files for different packages, including backack; you _can_ put files here, and Backpack will pick them up instead of the ones in the package; but by doing this you're renouncing any modifications on those files upon update; but in your case, since you want the theme to look different, it's ok;

Hope it helps.
Cheers!
