### ISSUE TITLE
Button color with other skin #18

### ISSUE THREAD

**Issue by danielbidala** [Laravel-Backpack/Base#319]
Hi @tabacitu 

Sorry but I have the same issue as #18 and not understand what to do exactly.

I republished my assets with php artisan backpack:base:install after I deleted adminlte and backpack folder in my public/vendor folder.

Or do I have to modify my backpack.base.css manually? Thx in advance.

**Comment by tabacitu** [comment]
Hmm... not sure what the problem is @danielbidala . Seems to work for me. Here's my process - in ```config/backpack/base.php``` I changed the AdminLTE skin from ```skin-purple``` to ```skin-blue```, and everything changed color, including the buttons:

![screen recording 2018-10-09 at 09 38 am](https://user-images.githubusercontent.com/1032474/46642029-77854600-cba7-11e8-81dd-1a3763b1a254.gif)


 Did you not get the same thing? If not, could you please provide more details on your process, or result?

Thanks, cheers!

**Comment by danielbidala** [comment]
Hi @tabacitu 

Yes, these two colors working fine for me too. But if you change to skin-green, the buttons will be blue.

**Comment by tabacitu** [comment]
Ah, ok, now I understand. Yes, it's a bit confusing, but: 
- for all skins, the default button is blue - that what AdminLTE decided. This is probably to keep in line with bootstrap convention (green = success, yellow = warning, red = danger);
- for the "purple" skin, which is a custom Backpack skin, the default button is purple - we decided to do this since the purple color does NOT conflict with any Bootstrap conventions;

So the blue default button on a green skin is the expected behaviour... however unintuitive it may be.

Hope it helps.
Cheers!
