### ISSUE TITLE
"CRUD" façade not available without user action, but present in examples 

### ISSUE THREAD

**Issue by aand18** [Laravel-Backpack/Base#347]
# Bug report

### What I did:
```
mkdir demo && cd demo
laravel new .
# added database prameters to `.env` file
composer require backpack/crud
php artisan backpack:base:install
php artisan backpack:crud:install
# answered 'no' to elFinder question
php artisan make:migration:schema create_tags_table --model=0 --schema="name:string:unique"
php artisan migrate
php artisan backpack:crud tag
```

Then, the example [here](https://backpackforlaravel.com/docs/3.5/crud-tutorial#generate-files) states:
```
# STEP 2. add a route for the crud panel (under the admin prefix and auth middleware): 
php artisan backpack:base:add-custom-route "CRUD::resource('tag', 'TagCrudController');"
```
Instead, I've added MANUALLY `CRUD::resource('tag', 'TagCrudController');` to the **custom.php** file.  

### What I expected to happen:
CRUD façade to work. 
### What happened:
 _Call to undefined function resource()_  
(because **CRUD** is undefined)
### Backpack, Laravel, PHP, DB version:
Backpack 3.5
Laravel 5.7.15

**Comment by tabacitu** [comment]
Hi @aand18 ,

Thanks for sharing your results. That's very weird - I just tried it myself and it worked for me. ```CRUD``` should be auto-registered by Laravel (feature introduced in Laravel 5.6).

(1) Can you please run ```php artisan backpack:base:version``` and let me know what the output is? 
(2) Also,  I see you've closed the issue - did you figure out what the problem was, in the meantime?

Cheers!

**Comment by aand18** [comment]
## sorry my mistake, I wrote by mistake `Crud:method`, missing a colon.
