### ISSUE TITLE
[Suggestion] adminlte/bower_components

### ISSUE THREAD

**Issue by reeslo** [Laravel-Backpack/Base#350]
This is a suggestion,

I have actually an when I deployed app to prod, a lot of file was not found, because my .gitignore has bower_components in.

Why don't use a compiled assets ?
Better than include entire (into git repository) "vendor/adminlte/bower_component" folder.
+40mo, +7000 elements for using 6 files.

**Comment by tabacitu** [comment]
Hi @reeslo ,

Sorry for taking so long to respond. Actually the ```bower_components``` folder is actively used in Backpack ([see here](https://github.com/Laravel-Backpack/Base/blob/master/src/resources/views/inc/scripts.blade.php#L7)). Since not everyone minifies and concatenates their JS, the components are used straight out of the ```bower_components``` folder. So eliminating it would break their apps.

I see two possible solutions for the "_too many files_" problem:
1) Load everything from CDNs (but I know you're against this).
2) We make a symlink to the folder in ```vendor``` (conversation here: https://github.com/Laravel-Backpack/CRUD/issues/1404)

As both have threads open, I'm going to close this issue. Let me know if you think I'm wrong to close this - it happens :-)

Cheers!
