### ISSUE TITLE
Question - How to show nested ressources in show view ? 

### ISSUE THREAD

**Issue by InfinityWebMe** [Laravel-Backpack/Base#353]
Hello,

I would like to add the nested ressources in the show view with a datatable.  

How can i do that ? I see how display nested ressources in a new page. 

Thank for this awesome work and for your help (in advance) :D

**Comment by tabacitu** [comment]
Hi @InfinityWebMe ,

You can [create a custom column](https://backpackforlaravel.com/docs/3.5/crud-columns#creating-a-custom-column-type) that shows any information you want from a relationship - that's most likely your best solution. 

Alternatively, you should also be able to use the ```text``` column with dot notation, in order to show _one_ attribute of a connected entry (ex: for product which hasOne category, use ```category.name``` as column name).

This is something I've been meaning to improve for some time. The plan for Backpack v4 is for relationship columns to automatically turn into links to those entities, if they have CRUDs.

Hope it helps.
Cheers!
