### ISSUE TITLE
I want to use a middleware instead of requiring a user to be logged in

### ISSUE THREAD

**Issue by vesper8** [Laravel-Backpack/Base#354]
I use a middleware on my apps that present a guest user with a "PIN" panel where they must enter a 6 digit number in order to gain access

I protect all my admin routes this way.. Horizon, Telescope, Totem, Log-Viewer etc

I would like to do the same for Backpack. I've already added the middleware by modifying the middleware_class and middleware_key in the base.php config file

I've commented out all the other middlewares too. This works, my PIN panel is shown. However Backpack still requires a user to be logged in to function properly

How can I disable this and not require a user to be authenticated in order to have full access?

**Comment by tabacitu** [comment]
Hi @vesper8 ,

Hmmm... I think a _quick hack_ would be to have just 1 user, and manually authenticate him in the middleware you're taking about, or in the PIN login process. Otherwise, you'd need to rewrite all controllers in Backpack/Base - which is the one that holds all authentication logic. 

Never thought you could do away with the "user" concept entirely, pretty clever. But Backpack wasn't meant to be used that way - it has users as default.

Hope it helps.
Cheers!
