### ISSUE TITLE
Proper way to customize included AdminLTE

### ISSUE THREAD

**Issue by DelightedD0D** [Laravel-Backpack/Base#357]
I needed to update the LESS variables for AdminLTE to match our branding and rebuild the assets. I'm new to grunt so it took me a while tonight to work out exactly how to accomplish this.

The below steps worked for me, but I have 2 questions:

- Is this the proper way to accomplish this?
- If it is, would it be possible/appropriate to include this in the backpack documentation somewhere?

# Modifying AdminLTE Includes

**NOTE:** _All commands are run on the host, not from within the VM_

Before making any changes, install grunt globally on your host machine

-    `npm install -g grunt-cli`

Move to the AdminLte directory

-    `cd my-project\public\vendor\adminlte\`

Pull down npm dependencies. This will set up grunt for the project itself. 
-    `npm install`  (only the first time)

Make any changes you need, probably in these files:
````
my-project/public/vendor/adminlte/build/less/variables.less   // Update styling 
my-project/public/vendor/adminlte/build/less/AdminLTE.less

my-project/public/vendor/adminlte/Gruntfile.js   // remove any includes we don't need
````

After changing the files, you'll need to run the build script to compile the assets 

-    `grunt less`

Profit

**Comment by tabacitu** [comment]
Hi @DelightedD0D ,

I don't think there's a "proper" way to customize AdminLTE, but **your way sounds very clean**. Your changes are strictly in the ```adminlte``` folder, so as long as you know you've changed it and don't overwrite it when upgrading, everything should work perfect in the future.

I've refrained from publishing docs about dependencies because it's a nightmare to maintain them, once there are any changes to the dependency, but I'll make sure to link to this thread if anybody asks, and give you full credit - thanks a lot for sharing your solution!

Cheers!
