### ISSUE TITLE
artisan route:list is not working with Backpack resetpasswordcontroller

### ISSUE THREAD

**Issue by abcflorida** [Laravel-Backpack/Base#358]
# Bug report
php artisan route:list throws error, other commands do not

### What I did:
execute php artisan route:list -v on command line

### What I expected to happen:
Show list of all routes

### What happened:
Got exception

These errors specifically point to the issue:
1   Backpack\Base\app\Http\Controllers\Auth\ResetPasswordController::__construct()
      [internal]:0

6   PDOException::("could not find driver")
E:\vm_shared_laravel\sites\voh\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:27

### What I've already tried to fix it:
I commented out line 50 -  or ResetPasswordController to see that this is the only problem line of code

if (!backpack_users_have_email()) {
       abort(501, trans('backpack::base.no_email_column'));
}

### Backpack, Laravel, PHP, DB version:
BP : 1.0.4
Lara: 5.6
DB: MySql 5.7.25

**Comment by tabacitu** [comment]
Hi @abcflorida ,

That's very weird. ```php artisan route:list -v``` works fine for me in all the tests.

I assume from the error that you had not finished setting up the database connection? So the app itself wasn't working either. Right? If so, I don't think that would be a problem - I _would_ expect the route list to work without an active db connection, but if it doesn't... I don't think it's too inconvenient. Backpack is only installed on projects that need a database. Otherwise it just doesn't make sense. And since the db connection setup is something that you only do at the start of the project (then forget about it), I think this would be a non-issue, so I'm going to close this.

Let me know if I'm wrong and you DB connection was working - in that case the issue might be different.

Cheers!

**Comment by tabacitu** [comment]
PS. Thanks for raising the issue though, open issues is how we learn how our software is used, and what we can do to improve it. I just think this one is a non-issue, I'm afraid. But I'm wrong all the time :-) Let me know if you think this is one of those cases.

**Comment by abcflorida** [comment]
I did set up the driver.  My app is fully functional.  Unless I try to use route:list.  Then I get this error:

$ php artisan route:list

   Illuminate\Database\QueryException  : could not find driver (SQL: select colu
mn_name as `column_name` from information_schema.columns where table_schema = vi
sions and table_name = users)

  at E:\vm_shared_laravel\sites\voh\vendor\laravel\framework\src\Illuminate\Data
base\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll
 format the error
    661|         // message to include the bindings with SQL, which will make th
is exception a
    662|         // lot more helpful to the developer instead of just the databa
se's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Backpack\Base\app\Http\Controllers\Auth\ResetPasswordController::__constru
ct()
      [internal]:0


It looks like the problem is that in the CLI, the DB connections.  I am using the default settings for laravel drivers and have not modified any backpack core files.  

return \Schema::hasColumn($user->getTable(), 'email');  This is the exact command that breaks the request.    

The reset password routes work fine from my app as HTTP.  This tells me it's something to do in cli bootstrapping ???

**Comment by tabacitu** [comment]
Huh - weird indeed, if it works on HTTP but not on CLI... Never heard of anything like this, I'm afraid, don't know where to begin to debug this :-) 

I see you're on Laravel 5.6, though - I recommend you upgrade to the latest Laravel (5.7, then 5.8) & Backpack (3.6), Laravel might have fixed some stuff in its releases since...

Sorry I couldn't be of more help.
Cheers!
