### ISSUE TITLE
Alert from FormRequest messages not apear

### ISSUE THREAD

**Issue by ihsanberahim** [Laravel-Backpack/Base#360]
# Bug report

### What I did:
i'm using `Illuminate\Foundation\Http\FormRequest` to validate request.

### What I expected to happen:
Expecting validation messages from `Illuminate\Foundation\Http\FormRequest::messages` alert

### What happened:
Non of the messages appear

### What I've already tried to fix it:
```
    /**
     * Configure the validator instance.
     *
     * @param  \Illuminate\Validation\Validator  $validator
     * @return void
     */
    public function withValidator(Validator $validator)
    {
        collect($validator->errors()->all())->each(function($error) {
            Alert::error($error)->flash();
        });
    }
```
### Backpack, Laravel, PHP, DB version:
```
laravel/framework                     v5.7.25
backpack/base                         1.0.4
backpack/crud                         3.5.14
```

**Comment by tabacitu** [comment]
Hi @ihsanberahim ,

Hmm... this might be a little confusing, I agree:
- ```FormRequest::messages``` are used to show error messages inside the forms (which are persistent - they should not disappear, otherwise users would forget what they need to do);
- ```Alert``` shows bubble notifications in the top-right corner of the screen, to notify the user that a specific event has happened, action has completed, etc;

I agree it's a little confusing, since they're both messages, but I don't think they should be merged. They handle different use cases - ```FormRequest::messages``` are for persistent messages in the create/update forms, whereas ```Alert``` is for notification bubbles.

Let me know if you think I'm wrong on this - I make mistakes all the time. But I'll close the issue until I'm convinced otherwise.

Cheers!
