### ISSUE TITLE
Custom Route leads into 403

### ISSUE THREAD

**Issue by kunoSchlonz** [Laravel-Backpack/Base#375]
# Bug report

### What I did:
i have a simple CRUDController PlayerCrudController with the Model Player
then i wrote a simple new method which should return the amount of players:
i want to use this controller in the dashboard

`    
public function count(){
        $numplayers = [];
        $numplayers["count"]=123;
        return json_encode($numplayers);
    }
`

then i added the route to custom.php

`
Route::group([
    'prefix'     => config('backpack.base.route_prefix', 'admin'),
    'middleware' => ['web', config('backpack.base.middleware_key', 'admin')],
    'namespace'  => 'App\Http\Controllers\Admin',
], function () { // custom admin routes
    **Route::get('player/count', 'PlayerCrudController@count');**
`

### What I expected to happen:
that i get **{count:123}** or similar

### What happened:
i get a 403 error

### What I've already tried to fix it:
add **$this->crud->allowAccess('count');**

### Backpack, Laravel, PHP, DB version:
backpack 3.6, laravel 5.8, php 7.2, mysql 5.5

**Comment by tabacitu** [comment]
Hi @kunoSchlonz ,

Sorry, we try to keep Github for Backpack bugs only. Not support requests on custom code, otherwise we'd spend all our time debugging individual projects. [Please try StackOverflow](https://stackoverflow.com/questions/tagged/backpack-for-laravel). 

But the Whoops page in your local environment should provide more detail to help you debug - it should tell you exactly what line triggers the 403 error. Which would give you a place to start. With the information available, I don't think there's a chance anybody can help you, they'd need more code from the controller and the entire error stack.

Cheers!
