### ISSUE TITLE
The package only matches Laravel 5.3.x

### ISSUE THREAD

**Issue by jordankobellarz** [Laravel-Backpack/Base#38]
Hello @tabacitu , thanks for this great package!

I've tried to install the package 3.0 on my project that is using Laravel 5.2 and on a fresh install of Laravel 5.2, but composer says that the version 3.0 is only compatible with Laravel 5.3.x. 

I think this issue could be corrected changing the required Laravel version on composer.json from `"laravel/framework": "5.3.*"` to `"laravel/framework": ">=5.2",`.

Thanks!

**Comment by tabacitu** [comment]
Hi @jordankobellarz ,

Yes, the latest versions, Backpack\CRUD 3.1.x and Backpack\Base 0.7.x are only compatible with Laravel 5.3. That's because there have been serious changes to the Auth from Laravel 5.2 to Laravel 5.3. So changing the requirement in composer.json won't fix it - it won't work.

If you need to install Backpack\Base on Laravel 5.2 you can do so with ```composer require backpack/base 0.6.x```. CRUD and other packages will then be resolved by composer, just follow the documentation. The Base documentation was wrong, it didn't specify 0.6.x, I've just updated it - thanks. 

But I don't think the Laravel 5.2 packages will receive any updates. It's very time-intensive to maintain Backpack as it is - takes me about at least 2-3 hours/day -  it would be even more difficult to maintain 2 separate versions. Believe me, I don't like this either, I need to upgrade a few more personal projects to Laravel 5.3 now. I've written [more about this here](https://github.com/Laravel-Backpack/CRUD/issues/107#issuecomment-246129221) - basically, I see no other way.

But [upgrading to Laravel 5.3](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0) is a lot less scarry than the documentation makes it to be, and the changes are trivial, mostly "replace-all" stuff. It took me 1.5 hours for a small project, ~2.5 hours for a medium-sized project. There's also a semi-automatic way to do it, [Laravel Shift](https://laravelshift.com/), but I haven't tried that myself.

Sorry if the lack of 5.2 support will make Backpack less useful for your project.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
