### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/Base#400]
Hi,
using a tutorial at `https://scotch.io/tutorials/how-to-add-googles-two-factor-authentication-to-laravel` and overriding the backpack default login and register controllers i was able to setup 2FA on registration, but on login when it asks for 2fa code, it keeps refreshing when i enter the code no matter the right code or the wrong one and if i put direct url to dashboard it doesnt ask for 2fa code.

i also have added middleware in the config.backpack.base.middleware_class

but still the same.

Has anyone here implemented it? or some module available? or if its going to be a part of v4? or any clue on how to implement it would be much appreciated.
Thanks.

@tabacitu @OwenMelbz @aaranmcguire

P.S sorry for the repost but i cant seem to figure this one out.. also tried asking on gitter but no response.

**Comment by tabacitu** [comment]
Hi @mpixelz ,

No, there are no plans for official 2FA in v4 at this time. 

But it shouldn't be too hard to implement by using your own auth instead of Backpack's, like you said. Might want to make sure upon login you're using the ```backpack``` guard.

Happy to promote a tutorial/blog post/smth if you get to the bottom of it and want to share your knowledge with others.

Cheers!
