### ISSUE TITLE
Disable Auth Controller

### ISSUE THREAD

**Issue by Eddy16391** [Laravel-Backpack/Base#423]
Hi guys, I just finished installing a new project based on Laravel 6 and Backpack 4.
Since I have to make a project to be used locally, is it possible to disable the authentication controller?
So as to avoid logging in and entering the dashboard directly when I go on the admin route.
Sorry if it's a silly question but I'm new to this world.

**Comment by Eddy16391** [comment]
Wrong place, sorry

**Comment by tabacitu** [comment]
Huh... that's an interesting question @Eddy16391 - I don't think I've seen this before. I guess you could do that, yes. In your particular case, it doesn't make sense to login, if the admin panel is only accessible from localhost. Make sure it's not accessible remotely through IP:port though. 

Backpack does require the admin user's info quite in a few places:
- the ```CheckIfAdmin``` middleware;
- the Requests, when the admin tries to save/update something;
- the top-right corner of the interface, to show the name & image;
- possibly other places... idk;

To completely remove the login, you could:

# Solution 1 - automatically login the admin

You could do that inside ```CheckIfAdmin```. If a user is not logged in, just login the first user, instead of doing ```respondToUnauthorizedRequest()```.

This would be a quick-and-dirty way to achieve a "_no login_" interface.


# Solution 2 - actually remove the concept of user

Start by:
- deleting the db table
- deleting the user model
- disabling the auth routes in your ```config/backpack/base.php``` file (set ```setup_auth_routes``` to false);
- changing the ```app/Http/Middleware/CheckIfAdmin.php``` middleware so it does NOT exclude guests from admin routes:
```diff
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
-        if (backpack_auth()->guest()) {
-            return $this->respondToUnauthorizedRequest($request);
-        }

-        if (!$this->checkIfUserIsAdmin(backpack_user())) {
-            return $this->respondToUnauthorizedRequest($request);
-        }
-
        return $next($request);
    }
```
- returning ```true``` in the authorization part of all form Requests;
- creating a file inside ```resources/views/vendor/backpack/base/inc/menu_user_dropdown.blade.php``` that is empty;

_I think_ that should do it, too. But there could be more places where the admin user is used. 

---

If it's just something you're toying with on localhost, I don't think spending the time to completely remove the concept of User is worth for you - just take the quick-and-dirty path 😄 

Hope it helps.
Cheers!

**Comment by Eddy16391** [comment]
Hi, I think the best solution is solution 1.

But I can't understand how to do it. How can I "just login the first user"?

Thank you!


Il 09/02/2020 09:18, Cristian Tabacitu ha scritto:

**Comment by tabacitu** [comment]
In your Admin middleware:
```php
    public function handle($request, Closure $next)
    {
        backpack_auth()->attempt(
            [
                'email' => 'admin@example.com',
                'password' => 'the-password-in-clear'
            ], $request->filled('remember')
        );

        return $next($request);
    }
```

**Comment by Eddy16391** [comment]
It seems to work.
Thanks so much!

*Edoardo Ceccarini*
Computer and Automation Engineer
Email: ceccarini.edoardo@gmail.com
Mobile: +39 331 263 5756


Il giorno lun 10 feb 2020 alle ore 08:35 Cristian Tabacitu <
notifications@github.com> ha scritto:
