### ISSUE TITLE
Move all references to the admin/ endpoint to the config file

### ISSUE THREAD

**Issue by bretvanhorn** [Laravel-Backpack/Base#45]
So with the app I am developing, I retrofitted it to Backpack about midway through the project, and we don't want to have the /admin endpoint in our path, because it's all locked down anyhow. I'm finding that in Base and some of the other files and add-ons, admin is hardcoded into the vendor files. I would love to see Base and all of the other packages (CRUD, Permissions Manager, etc.)  pull the root URL from the config file so I don't have to update them all manually anytime I update my repos, or push a fresh build to staging or production. I would do it myself and submit a pull request, but I am tapped for time at the moment, so I'll just throw this out there as a friendly suggestion and maybe I can come back to it later if y'all don't have time. :-) BTW, Backpack is an amazing suite of tools. Thanks so much for making it open source!

**Comment by OwenMelbz** [comment]
I think this is something that @tabacitu is working through, and is actually tagged as help wanted

https://github.com/Laravel-Backpack/CRUD/issues/129

So anybody who wants to submit PR based off the above fix would be helping out massively :)

**Comment by bretvanhorn** [comment]
Awesome. If I have some free time over the next week and it hasn't been tackled, I'll see if I can get it taken care of.

**Comment by tabacitu** [comment]
Hi guys - yes, this could be an issue. Haven't had time to properly go through every mention of admin, in all packages, and see if it uses the config value. There have been some pull requests for this and they've all been merged, but there might be a few slips too. 

Any help on this is greatly appreciated. Being such a clear PR, the merge would also go down smoothly from the GitHub interface.

Otherwise, let's leave this open until we find the time to do it.

Thanks, cheers!
