### ISSUE TITLE
Configurable auth Guard

### ISSUE THREAD

**Issue by pavoltanuska** [Laravel-Backpack/Base#46]
I'm used to having my admin users in separate table and leaving the default `users` table for frontend users only.

I've configured the `config/auth.php` file accordingly (admin guard, admin provider).

Just for clarity, I'm using Laravel 5.3.

The Backpack Auth controllers are using the default guard (as provided by, for example, [Illuminate\Foundation\Auth\AuthenticatesUsers->guard()](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Auth/AuthenticatesUsers.php#L157) method which points to the default guard - as configured in `config/auth.php`), but I'd like to use my own dedicated admin guard.

What I've done to accomplish that:
- I've copied all the Backpack's Auth controllers to `App\Http\Controllers\Admin` together with `AdminController`
- extended the Backpack's Auth controllers and I've overriden just the `guard()` method to return `Auth::guard('admin')`
- for `AdminController` I overrode (what a weird word) the `__construct()` method to:

```
public function __construct()
{
    $this->middleware('admin:admin');
}
```

which passes the "admin" guard attribute to the [Admin Middleware](https://github.com/Laravel-Backpack/Base/blob/master/src/app/Http/Middleware/Admin.php).
- I've disabled the routes creation in `config/backpack/base.php` and specified my own routes accordingly.
- changed the `Auth::check()`s in provided views to `Auth::guard('admin')->check()`

It works ok and isn't much of a hassle (even more when after that I have a ready-to-go CRUD package - thanks for that) and I think that this approach also confirms Issue https://github.com/Laravel-Backpack/Base/issues/25

But it could be even easier (for us, lazy programmers) with a configurable guard in `config/backpack/base.php`. It's value could be `null` by default, so it wouldn't change anything if you wouldn't want to have a separate guard.

What do you guys think?

I saw (in https://github.com/Laravel-Backpack/Base/issues/44) that you aim to provide an easy way to put the Controllers to the project files via artisan, so I'm not sure if this "config approach" is a valid usecase for the project in general (and worth a PR, of course), or if it's more of an edge case that should be handled the way I did it on my project (by extending the default Controllers).

**Comment by OwenMelbz** [comment]
It should be included already in https://github.com/Laravel-Backpack/Base/pull/87

**Comment by nwrman** [comment]
On Laravel 5.4 I got it to work based on the comment from @pavoltanuska, but rather than copying all the controllers I extended all of them on my own namespace `App\Http\Controllers\Admin` 

To make admin password reset work with the custom `admin` Guard I also had to overwrite the broker function on the `ResetPasswordController`:

```PHP
public function broker()
{
    return Password::broker('admins');
}
```

And on `config/auth.php` add a new entry matching the `admin` Guard:

```PHP
'passwords' => [
        'users'  => [
            'provider' => 'users',
            'table'    => 'password_resets',
            'expire'   => 60,
        ],
        'admins' => [
            'provider' => 'admins',
            'table'    => 'password_resets',
            'expire'   => 60,
        ],
    ],
```

**Comment by antonino-ferreira** [comment]
I managed to get separate logins working kind of the same way (also on Laravel 5.4), except that I created another midleware named 'admin' that uses the admin guard… 

It works as far as logging in, registering, etc goes it works but can't fully use PageManager for instance because when the forms are submitted  the Requests also have 'Auth::check()' hard coded in them. I suppose I could create my own CRUD for managing pages and then have control over the Requests but I wouldn't fancy doing the same for the permission manager one!

Is there a way to get this working ? am I missing something?

PS: btw, I tend to agree with @OwenMelbz, it would be very helpful to have this in the base. Most projects that I can think of using this for would need that.

**Comment by Samuelbdesouza** [comment]
Hello, I'm starting to use Laravel and I'd like to know how to differentiate the Admin guard from the User Guard using the same login form!

**Comment by OwenMelbz** [comment]
There's already a PR which allows this. We're waiting feedback :)

**Comment by vkovic** [comment]
I was just playing around and since i have 2 guards already in the project, i tried to override default backpack login controller as @pavoltanuska suggested. But in the middle of "overriding" i realized that i already have my 2 login controllers with guards fully functional and that default guard is set to one of them (config/auth.php), so i just replaced it with:

    return [
        'defaults' => [
            'guard' => 'admin',
            'passwords' => 'admin'
        ],
        // ...
    ];

  and everything just started working ... Maybe it may help some of you guys, as a quick fix ...

**Comment by lloy0076** [comment]
This appears to be related to #165; I'm not sure this needs to remain open.

Please reopen if needed.
