### ISSUE TITLE
[ask] Login with username or email

### ISSUE THREAD

**Issue by rdlimosin** [Laravel-Backpack/Base#55]
Hello, i really appreciate this work

i just want to know: how to login with username or email?

thanks

**Comment by tabacitu** [comment]
Hi @rdlimosin ,

I think you can:
(1) Use [this procedure](https://github.com/Laravel-Backpack/Base/issues/25#issuecomment-238011374) to extend the Auth controllers in Backpack; Please note the instructions are for Laravel 5.2, there are a few more controllers in 5.3 but it's very very similar.
(2) Do something like this in those controllers: https://laracasts.com/discuss/channels/general-discussion/log-in-with-username-or-email-in-laravel-5

Cheers!

**Comment by CHOMNANP** [comment]
For Laravel 5.5, I'm curious how can we implement this?

**Comment by MarcosBL** [comment]
+1 here, how to for Laravel 5.5 ?

We want to use backpack base + CRUD in a simple project where we must extended a legacy app (6+ years old ExtJS app, just imagine) , and we must use their users database. We managed to define a connection to their database in the User model, plus the table, but the problem is their "email" fields is a `userName`, and their password field is a `password`... but MD5'ed, not BCRYPTed like in Laravel.

Any ideas ? How can I extended Backpack auth to use the `userName` field + md5 password ? Been looking around github issues but couldn't find a "this is the correct way to do it", at least not a recent Laravel 5.5 way.

**Comment by tabacitu** [comment]
@MarcosBL the procedure should be similar. Basically you should be able to use your own Authentication controllers instead of the Backpack ones. Just that now it's easier than ever to overwrite the Backpack\Base routes, just create a ```routes/backpack/base.php``` file and Backpack will pick it up.

**Comment by MarcosBL** [comment]
Thanks @tabacitu !

I managed to get it working, and explain here how, just for anyone facing the same situation.

I deactivated

````php
'setup_auth_routes' => false,
````

Then I created my own login view (a simple login form) in `resources/views/auth/login.blade.php` using `userName` and `password` (the old system names) and pointed some routes to it:

````php
Route::group(['middleware' => 'web', 'prefix' => config('backpack.base.route_prefix')], function () {
    /* Custom auth */
    Route::auth();
    Route::get('auth/login', 'Auth\LoginController@login');
    Route::post('auth/login', 'Auth\LoginController@postLogin');
    Route::get('logout', 'Auth\LoginController@logout');
    Route::get('dashboard', '\Backpack\Base\app\Http\Controllers\AdminController@dashboard');
    Route::get('/', '\Backpack\Base\app\Http\Controllers\AdminController@redirect');
    /* End */
});
````

Created the `app/Http/Controllers/Auth/LoginController.php` file:

````php
<?php

namespace App\Http\Controllers\Auth;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
	use AuthenticatesUsers;

	protected $redirectTo = '/admin/dashboard';
	protected $redirectToFailed = '/admin/login';
	protected $username = 'userName';

	public function __construct()
	{
		$this->middleware('guest')->except('logout');
	}

	public function username() {
		return $this->username;
	}

	public function postLogin(Request $request)
	{
		/* Helper variable */
		$username = $this->username();
		/* Validation rules for the form */
		$input = \Input::only($username, 'password');
		$rules = [
			$username => 'required',
			'password' => 'required'
		];

		$validator = \Validator::make($input, $rules);
		if($validator->fails())
		{
			return \Redirect::to($this->redirectToFailed)->withInput()->withErrors($validator);
		}
		/* Custom auth */
		$user = \App\User::where($username, $request->$username)
		->where('password',md5($request->password))
		->first();

		if ($user) {
			/* Manual login if found */
			\Auth::loginUsingId($user->id);
			return \Redirect::to('/admin/dashboard');
		}
		else
		{
			return \Redirect::to($this->redirectToFailed)->withErrors([$username => "Wrong user or password"]);
		}
	}

	public function logout(Request $request) {
		/* Custom logout */
		\Auth::logout();
		return \Redirect::to($this->redirectToFailed);
	}
}
````

That worked fine (not sure if redundant code, that's why I was asking), I only needed to specify the connection, table name, etc, in User model:

````php
	protected $connection = 'mysql_remote'; /* remote connection config defined in database.php */
	protected $table = 'usuario'; /* remote table name */
	protected $primaryKey = 'id'; /* remote table primary id */
````

I found a problem with the remember_token, the old database doesn't have that field, so it breaks the app when you logout, as it tries to update it. I managed to solve it by adding this to the User model:

````php
    /* Allows us to ignore the remember_token database field */
    public function setAttribute($key, $value)
    {
    	$isRememberTokenAttribute = $key == $this->getRememberTokenName();
    	if (!$isRememberTokenAttribute)
    	{
    		parent::setAttribute($key, $value);
    	}
    }
````

I'm pretty sure there must be a better way, but this was what I could achieve

**Comment by nakamuraagatha** [comment]
Great @MarcosBL !
this work for me. thanks

**Comment by iMokhles** [comment]
thanks @MarcosBL but this code specially for the password statement will fail if the the password is hashed using` bcrypt()` ?
```
$user = \App\User::where($username, $request->$username)
		->where('password',md5($request->password))
		->first();
```

right ?
