### ISSUE TITLE
Use roles/permissions the best way

### ISSUE THREAD

**Issue by gabva** [Laravel-Backpack/Base#60]
Hi 

Thank you for this great work.

I'm trying backpack and i would like to use permissions for all the system, specially for the  native packages (in /vendor) example : 
-  prevent user to have access to elfinder, or user,roles,permission, ...
- or even ideally  access  forbidden to the admin panel entirely ( my users can register  on the frontend too )

I know i can do it directly in the controller when i am in App/ (ex : new crud i've made myself) but the best way to manage the vendor/  ones ? 

Thanks for your advices

**Comment by tabacitu** [comment]
Hi @gabva ,

Glad you like it :-)

Right now you should be able to do it like this:
1. In ```config/backpack/base.php``` set ```setup_auth_routes``` and ```setup_dashboard_routes``` to false.
2. Register the Base routes in your routes file:
```php
Route::group(
                [
                    'middleware' => 'web',
                    'prefix'     => config('backpack.base.route_prefix'),
                    'namespace'     => '\Backpack\Base\Http\Controllers',
                ],
                function () {
                    // setup the auth routes
                    Route::auth();
                    Route::get('logout', 'Auth\LoginController@logout');

                    // setup the dashboard routes
                    Route::get('dashboard', 'AdminController@dashboard');
                    Route::get('/', 'AdminController@redirect');
                });
```

The routes above are just an example, you could put each route under a different middleware, for example under a ```can:view.elfinder``` middleware, [something like this](https://github.com/spatie/laravel-permission#using-a-middleware). Or you could create controllers that extend the ones in Base so that you can do whatever you want in them, and point the routes there instead of the controllers in ```\Backpack\Base\Http\Controllers```.

You may be onto something, this may not be the easiest way to do this. Anyone else has any idea of how we could make this easier in the future? I think an intuitive way would be to have an "extend" command across the board (all packages) which would create in ```app``` some controllers, models, requests etc that extend the ones in the vendor folder. That way the developer can do whatever he wants. What do you think?

**Comment by gabva** [comment]
hi @tabacitu 

Thanks a lot for this answer.
It's quite easy, even if you're right we should think to an easier way to extend the native controllers

**Comment by tabacitu** [comment]
I think I found a solution. Noted it as a separate issue, #101. Cheers!
