### ISSUE TITLE
can not change users table name

### ISSUE THREAD

**Issue by appdezign** [Laravel-Backpack/Base#70]
It is quite easy to change the users table in Laravel 5. But when I use Backpack Base, and I try to register, I still get an Error:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `email` = me@example.com)`

When I look at the RegisterController.php, I see that the users table name is hard coded in the validator method:

`
return Validator::make($data, [
    'name'     => 'required|max:255',
    'email'    => 'required|email|max:255|unique:users',
    'password' => 'required|min:6|confirmed',
]);
`

It would be nice to have the users table name in the config (just like the permission package).

**Comment by OwenMelbz** [comment]
Have you changed the table in your User model?

**Comment by appdezign** [comment]
Yes, I have changed the name in the User model. And I think Backpack Base does more than styling for auth. The controllers of the Backpack Base package are used, when you login or register.

When I change the user table name in RegisterController, everything works fine, but I don't want to change anything in the vendor directory, of course.

**Comment by pavoltanuska** [comment]
> I don't want to change anything in the vendor directory

@appdezign You can always create your own controller (e.g. Http/Controllers/Admin/Auth/RegisterController.php), extend ```Backpack\Base\app\Http\Controllers\Auth\RegisterController.php``` and rewrite the validator only. Nothing needs to be changed in vendor directory this way.

**Comment by mpixelz** [comment]
Hi,
im going through a similar issue.. i have added few more fields in my user table.. and have also changed the model file to include the fields to fillables but when i use the user list in backpack.. the form doesnt display those fields automatically.. 
there is no backpack usercrud available to alter and modify it instead of changing the vendor folder crudcontroller?

**Comment by tabacitu** [comment]
@appdezign , you're totally right, it's a good thing to abstract the validator rules so we won't need to overwrite it when changing the Users table. 

It's now fixed in Backpack\Base ```0.7.13```. No need to specify the user table again, just make sure the correct FQDN is specified for the User model in ```config/backpack/base.php```. It will take the table name from the User model.

Cheers!

**Comment by appdezign** [comment]
Excellent. Thank you.
