### ISSUE TITLE
[IDEA] - Allow 2FA plugins/modules

### ISSUE THREAD

**Issue by aaranmcguire** [Laravel-Backpack/Base#76]
I came here after I saw it featured on the Laravel Newsletter, it looks very cool and I think I'll end up using this in an upcoming project, but I noticed there is no feature for 2FA (2 Factor Auth). Being an 'admin dashboard '  I think it would be useful to make is easy to enable 2FA.

If you want I could investigate the best ways to do this (so that anyone could create their own 2FA module); here are a few types of 2FA I'd like to enable:

- OTP (One Time Password)
- TOTP (Time-based One-time Password)
- FIDO U2F (Using Yubi Keys)

**Comment by OwenMelbz** [comment]
Does sound good :) although the package just uses laravels native authentication with an adjusted email template and templates.

So if the suggested method hooks into the the default laravel auth or can easily be toggled on/off then would be good :)

**Comment by tabacitu** [comment]
Hm... that does sound like an improvement. Admin panels _should_ be more secure then they are right now, I agree. But there are a few things that worry me about 2FA today:
- doesn't 2FA with one of those third parties usually cost? 
- the landscape seems divided with so many vendors and preferences;

I think a first step toward making this easier to use not only for Backpack projects (backends), but also for the end user (front-ends), would be to create a 2FA package for Laravel, that would support a few vendors and have "adapters" for everybody else. Like [Omnipay](http://omnipay.thephpleague.com/) or [Laravel notifications](https://laravel.com/docs/5.3/notifications). That would definitely popularize 2FA in the PHP/Laravel landscape and it would then make a lot of sense to use it by default in Backpack, too.

That being said, since I don't know about any one package that does that (yet), I was thinking that a few simpler solutions to the same problem might be:
1) Oauth;
2) [Passwordless](https://medium.com/@ninjudd/passwords-are-obsolete-9ed56d483eb#.w0ghysmk3) [authentication](https://www.sitepoint.com/passwordless-authentication-works/); 

I personally like both over standard 2FA, because:
1) Oauth with Fb, Google, Github, etc would be a one-click login for most users (they're already logged into those services), as opposed to two-step (2FA), while actually providing the security those services offer (most will force 2FA pretty soon).
2) Passwordless does not require a third party to operate. We'd just send an email. It's still two steps, though.

What do you guys think?

**Comment by OwenMelbz** [comment]
Haven't had a chance to look into 2-step/factor as a whole, but I imagine authy or google autheneticator are free?

We'd need to also consider if we'd want a mechanism which supports internet-less authentication, eg. A few of our higher profile clients servers have outgoing internet blocked. Meaning you couldn't curl any remote systems to authenticate. So that's one thing to consider.

We actually a custom SSO solution for all our sites. We use Google account to login to all our CMSs in a pretty simple fashion. So looks for a email in the database matching the authenticated google account then lets you in (it does an API check with google though to prove its authenticity) then we have 2 step authentication on all our google accounts.

I think the easiest method would be to implement google/Facebook etc. however that would be a right pain for developers setting up apps and API keys every time. So I guess my first step would be to look into Authy wrapper like https://github.com/rinvex/laravel-authy/blob/master/README.md

**Comment by aaranmcguire** [comment]
So, the most popular versions of 2FA don't require communication with external providers. TOTP is just an algorithm. We'd provide the user with a QR code and they can use whatever app they want to get the code. The Laravel application would then just run an algorithm and check if it matches what the user inputted. 

```
TC = floor((unixtime(now) − unixtime(T0)) / TS),
TOTP = HOTP(SecretKey, TC),
TOTP-Value = TOTP mod 10d, where d is the desired number of digits of the one-time password.
```

**Comment by OwenMelbz** [comment]
Ah okay, recon is easy enough to roll yourself, or have any recommended packages? I assume there's still a step where the user has to link their account to an authenticator as well?

**Comment by aaranmcguire** [comment]
Yh, I can take a look this later this week. The only think that would be required (from the end users perspective) is to have an app that can give TOTP codes. I use Authy, but Google Authenticator works too, and I'm sure there are others. But I can create is as a contract, we could have a bunch of 2FA methods and let the user select what's best for them.

**Comment by zschuessler** [comment]
2FA is one of those features you need for enterprise. I would be fine it not being in the Backpack package until other enterprisey features are implemented (like a test suite).

For those that need 2FA now, more than likely they already have a provider in mind that easily integrates with PHP/Laravel.

**Comment by tabacitu** [comment]
@zschuessler , I think you bring up some good points. Unit testing is definitely a priority over this, but no harm in talking about it  :-)

I think the next question is - how can we implement 2FA or Oauth so that only the users who want it would have it?

1) inside the package and it will only run if certains configs are set?
2) as a different controller that extends LoginController/RegisterController, and you use the one you want?
3) as a separate package?
4) as a code snippet/tutorial?

**Comment by Dynamo6** [comment]
Hey guys, did you have any further thoughts on this? We'd love to see 2fa in backpack :) You can find a Laravel compatible 2fa library at https://github.com/antonioribeiro/google2fa. Many thanks!

**Comment by lloy0076** [comment]
@tabacitu - it depends on how "monolithic" the Backpack pakages are meant to be:

1. Are they **just** admin panels that make creating **admin panels** a lot easier?
2. Is Backpack responsible for everything else such as *authentication* too?

Perhaps, to explain myself.

If we took the first path, then it's **not** up to any of the Backpack modules to provide any more authentication help than Laravel itself does. In fact, at the moment this is the case and the only real alteration to Laravel's default authentication is to ensure a password reset is sent to the correct URL/route.

If 2FA were to "appear" I'd argue that it would be a separate and *optional* package given that, even in this current discussion, there seems no quick consensus as to what type of 2FA should be default.

**Comment by tabacitu** [comment]
@lloy0076 - I think you've touched an important issue. I think keeping the Backpack packages simple is the best way to go. The entire "_raison d'etre_" for Backpack is the idea that it's better to build from the basics up, rather than take something bloated and strip it down. Makes for better code and is faster in most cases.

That being said, I do think 2FA would be a good addition for many admin panels, so I would love it if Backpack had an easy-to-use way to achieve that. I don't know if as a base feature, as a separate package or a tutorial, but I think it's important.

THAT being said, I don't see it happening before there's "_one 2FA package to rule them all_", [as I mentioned in my previous comment](https://github.com/Laravel-Backpack/Base/issues/76#issuecomment-269164966). Since there are so SO many implementations, and none seems better than the rest, it's just a matter of opinion, I think it's better to have NO implementation, rather than an implementation that will cause people pain to overwrite.

To conclude:
- I wish there were one 2FA package we could integrate that had "adapters" and satisfied everyone;
- I would love to create such a package, but definitely don't have the time, since I already spend A LOT of time on Backpack;
- if anybody creates such a package (official Laravel package or otherwise) and it's stable, I'd love to use it in Backpack;
- until then, let's table this discussion;

Cheers!

**Comment by mpixelz** [comment]
Hi,
using a tutorial at `https://scotch.io/tutorials/how-to-add-googles-two-factor-authentication-to-laravel` and overriding the backpack default login and register controllers i was able to setup 2FA on registration, but on login when it asks for 2fa code, it keeps refreshing when i enter the code no matter the right code or the wrong one.

Has anyone here implemented it? or some module available? or if its going to be a part of v4? or any clue on how to implement it would be much appreciated.
Thanks.

@tabacitu @OwenMelbz @aaranmcguire
