### ISSUE TITLE
laravel/socialite integration

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/Base#79]
I am wondering if Backpack is going to adopt laravel/socialite for a part of login system. 
I get an error telling `Class 'App\Http\Controllers\Auth\Auth' not found`

```
namespace App\Http\Controllers\Auth;

use Socialite;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AuthController extends Controller
{
    
    public function __construct()
    {
        //$this->redirectPath = route('admin/dashboard');
    }

   /**
     * Redirect the user to the GitHub authentication page.
     *
     * @return Response
     */
    public function redirectToProvider()
    {
        return Socialite::driver('google')->redirect();
    }

    /**
     * Obtain the user information from GitHub.
     *
     * @return Response
     */
    public function handleProviderCallback($provider)
    {
        $user = Socialite::driver($provider)->user();
        
        // stroing data to our use table and logging them in
        $data = [
            'name' => $user->getName(),
            'email' => $user->getEmail()
        ];

        Auth::login(User::firstOrCreate($data));
        return redirect(config('backpack.base.route_prefix').'/dashboard');
        //after login redirecting to home page
        //return redirect($this->redirectPath());
    } 
}

```

**Comment by OwenMelbz** [comment]
I cant answer for @tabacitu but my opinion would be probably not.

Backpack to me is a Admin CRUD Framework - which inherently is a secure/locked down area.

Where as socialite acts as a easy way for people to authenticate with your application and social media. (which also require you to set up applications on facebook/google/twitter etc thats an extra step)

Those two things in my mind are separate concepts, you wouldn't mix them together as socialite was designed for frontend applications.

So I'd say probably not on the roadmap for core feature of backpack. HOWEVER. There is a community section or the website which content can be submitted to e.g Tutorials. so thats not to say if somebody was to write an article/provide code snippets how to integrate socialite into their admin it wouldnt be able to be listed :)

I will actually close this - as this is an area for backpack related issues, and as this isn't actually an issue with the package itself, but @tabacitu will see it and be able to give his feedback soon im sure :)

If you're having any troubles actually using socialite then its best to ask on StackOverflow which has a much larger range of people who are able to help you with your specific issue, as github issues are designed for package specific issues/bugs, rather than general help/debugging - you can use the tags as listed on the Backpack homepage -> http://stackoverflow.com/questions/tagged/backpack-for-laravel

**Comment by shinokada** [comment]
Thanks Owen.

I used this and it works now. I also extended Backpack's LoginController.

```
<?php

namespace App\Http\Controllers\Auth;

use Socialite;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Backpack\Base\app\Http\Controllers\Auth\LoginController as BackpackLoginController;
use App\User;

class AuthController extends BackpackLoginController
{
    use AuthenticatesUsers;


    public function __construct()
    {
        parent::__construct();
        //$this->redirectPath = route('admin/dashboard');
    }

    public function showLoginForm()
    {
        $this->data['title'] = trans('backpack::base.login'); // set the page title
        return view('auth.login', $this->data);
    }

    /**
     * Redirect the user to the GitHub authentication page.
     *
     * @return Response
     */
    public function redirectToProvider()
    {
        return Socialite::driver('google')->redirect();
    }

    /**
     * Obtain the user information from GitHub.
     *
     * @return Response
     */
    public function handleProviderCallback($provider)
    {
        $user = Socialite::driver($provider)->user();
        $data = [
            'email' => $user->getEmail()
        ];

        Auth::login(User::firstOrCreate($data));
        return redirect(config('backpack.base.route_prefix').'/dashboard');
    } 
}

```

**Comment by OwenMelbz** [comment]
Cool :) nice one.

Out of interest why would you have your admin area usable by anybody via social media?

**Comment by shinokada** [comment]
It is not usable for everyone. It is only for who has account or the site has a registered email.

**Comment by OwenMelbz** [comment]
But your code says 'User::firstOrCreate' so if the user doesn't exist, it will let anybody register and get into your admin?

**Comment by shinokada** [comment]
Thanks Owen. I just updated the previous post adding try/catch as well.
