### ISSUE TITLE
Suggestion: Adding general words to Base/src/resources/lang/en/base.php

### ISSUE THREAD

**Issue by shinokada** [Laravel-Backpack/Base#81]
In Base/src/resources/lang/en/base.php, adding general words.

```
return [
    ...
    ...
    // side menu
    'dashboard' => 'Dashboard',
    'slides' => 'Slides',
    'blog'=> 'Blog',
    'articles' => 'Articles',
    'categories' => 'Categories',
    'tags' => 'Tags',
    'pages'=>'Pages',
    'menu'=>'Menu',
    'user_roles_permissions'='User, Roles, Permissions',
    'users'=>'Users',
    ....
    // and more for other views
    ...
];
```

And using then in views. e.g. Base/src/resources/views/inc/sidebar.blade.php

```
<li><a href="{{ url('admin/dashboard') }}"><i class="fa fa-dashboard"></i> <span>{{ trans('backpack::base.dashboard') }}</span></a></li>
<li class="treeview">
<a href="#"><i class="fa fa-newspaper-o"></i> <span>{{ trans('backpack::base.articles') }}</span> <i class="fa fa-angle-left pull-right"></i></a>
    <ul class="treeview-menu">
          <li><a href="{{ url('admin/article') }}"><i class="fa fa-newspaper-o"></i> <span>{{ trans('backpack::base.articles') }}</span></a></li>
          <li><a href="{{ url('admin/category') }}"><i class="fa fa-list"></i> <span>{{ trans('backpack::base.category') }}</span></a></li>
          <li><a href="{{ url('admin/tag') }}"><i class="fa fa-tag"></i> <span>{{ trans('backpack::base.tags') }}</span></a></li>
...
...

```

This makes easier for localization.

**Comment by OwenMelbz** [comment]
Hi do you not think that's a bit niche?

Only because I've used backpack for 3 large projects now and have needed none of those suggestions.

What might be better is if you create your own github project/package and create a library of words with translations so people can download and install theirselves?

@tabacitu might have an idea also.

I'll close this to keep the area tidy as it's not actually an issue, but feel free to keep replying etc!

**Comment by tabacitu** [comment]
Hmm... this makes a lot of sense to me, especially as we're moving towards a completely multi-language system.

@OwenMelbz , you might not have needed this if all your admin panels were in English. So have mine, because all our recent clients have been English-speaking. But this won't always be the case, so I think we should cater to other languages too.

----

One question that arises, though, is WHERE to place those general words. Placing everything in Backpack\Base's lang file is easier, but it would be a modularity breach, since the actual "Pages", "Tags", "Categories", etc are in separate packages.

So I guess the best way to go would be to create language files for each package, and place them there. That way, you won't have unused language keys.

Thoughts?

**Comment by OwenMelbz** [comment]
I may not be on the same page as you two then lol, when you say general words, are you meaning "translate backpack" or are you saying adding generic words like chicken, pizza, boat ?

I'm fine with translating backpack fully, however was thinking if its actually generic words like the above, then surely thats large amount of maintenance and code bloat for something that might not be needed?

**Comment by tabacitu** [comment]
Oh, completely agree, I don't think @shinokada  proposed translating general words, only words that we actually use in Backpack packages.

But if we do go crazy and create a dictionary inside lang files, I say we start with "supercalifragilisticexpialidocious". I like a good translating challenge :-)

**Comment by OwenMelbz** [comment]
Ha well if thats the case then yeah, it would make sense. I think the words should be kept into package related context though, as I wouldnt want all Category/Tag etc related translations in my application, when they serve no relevance! :)

**Comment by shinokada** [comment]
Yes, as I gave in the example above, I was talking about words used in Backpack packages. And I thought it should be in each package as tabacitu wrote. Anyway I am happy to know that this is adopted for a new version. Let me know if you need a help.

**Comment by tabacitu** [comment]
Guys, just went through all Base blade files and didn't find anything that hasn't been translated, so I think this issue is good to close.

Cheers, thanks for the help!
